"use client";

import { useState, useEffect } from "react";
import { X, Sparkles, Send, ExternalLink, ChevronRight, Bot, RefreshCw } from "lucide-react";

interface AdIntentDrawerProps {
  isOpen: boolean;
  topic: string;
  onClose: () => void;
}

// Map of instant descriptions for topics generated by Gemini AI
const GEMINI_TOPIC_DESCRIPTIONS: Record<string, string> = {
  "Redes sociales":
    "Las redes sociales han transformado la forma en que las personas se conectan, comparten información y consumen contenido digital. Sirven como plataformas interactivas donde los usuarios crean comunidades, construyen identidades digitales y difunden tendencias globales en tiempo real.",
  "Historia":
    "El análisis histórico examina los acontecimientos pasados para comprender el origen de las estructuras sociales actuales. A través del estudio de documentos, relatos y hallazgos, la historia rescata pasajes olvidados y ofrece lecciones fundamentales para el futuro.",
  "Calculadoras y herramientas de referencia":
    "Las herramientas de referencia y calculadoras digitales facilitan la toma de decisiones basada en datos precisos. Permiten realizar conversiones complejas, proyecciones financieras y consultas técnicas de manera instantánea.",
  "Psicología":
    "La psicología estudia la conducta humana, los procesos mentales y la percepción emocional. Nos ayuda a entender cómo reaccionamos ante situaciones de estrés, la dinámica de las relaciones interpersonales y la toma de decisiones cotidianas.",
  "Tecnología":
    "La tecnología abarca los avances en software, inteligencia artificial y computación que automatizan tareas, mejoran la conectividad y potencian el desarrollo económico global.",
};

export default function AdIntentDrawer({ isOpen, topic, onClose }: AdIntentDrawerProps) {
  const [messages, setMessages] = useState<Array<{ sender: "gemini" | "user"; text: string }>>([]);
  const [inputQuery, setInputQuery] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    if (topic) {
      const initialDesc =
        GEMINI_TOPIC_DESCRIPTIONS[topic] ||
        `El término "${topic}" abarca conceptos clave dentro de esta lectura. A través de este resumen asistido por inteligencia artificial, puedes explorar su contexto y aplicaciones en la sociedad moderna.`;

      setMessages([
        {
          sender: "gemini",
          text: initialDesc,
        },
      ]);
    }
  }, [topic]);

  if (!isOpen) return null;

  const handleSendPrompt = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputQuery.trim() || isGenerating) return;

    const userText = inputQuery;
    setInputQuery("");
    setMessages((prev) => [...prev, { sender: "user", text: userText }]);
    setIsGenerating(true);

    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          sender: "gemini",
          text: `Respuesta de Gemini sobre "${userText}": En relación con ${topic}, los análisis sugieren que este aspecto impulsa el interés del lector y proporciona información de gran valor conceptual.`,
        },
      ]);
      setIsGenerating(false);
    }, 800);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden font-sans">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/40 backdrop-blur-xs transition-opacity"
        onClick={onClose}
      />

      {/* Side Drawer Panel */}
      <div className="fixed inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-lg bg-white dark:bg-gray-900 border-l border-gray-200 dark:border-gray-800 shadow-2xl flex flex-col justify-between overflow-hidden">
          
          {/* Drawer Header (Gemini AI Header) */}
          <div className="p-4 bg-gradient-to-r from-gray-900 via-slate-900 to-indigo-950 text-white flex items-center justify-between border-b border-gray-800">
            <div className="flex items-center space-x-2.5">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-blue-500 via-indigo-500 to-purple-500 flex items-center justify-center text-white shadow-sm">
                <Sparkles className="w-4 h-4 animate-pulse" />
              </div>
              <div>
                <div className="flex items-center space-x-1.5">
                  <h3 className="font-bold text-sm text-white">{topic}</h3>
                  <span className="text-[10px] font-semibold bg-blue-500/30 text-blue-300 border border-blue-400/30 px-2 py-0.2 rounded-full">
                    Generado por Gemini
                  </span>
                </div>
                <p className="text-[11px] text-gray-400">Asistente de inteligencia artificial de Google</p>
              </div>
            </div>

            <button
              onClick={onClose}
              className="p-1.5 text-gray-400 hover:text-white rounded-xl hover:bg-gray-800 transition"
              title="Cerrar ventana lateral"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Drawer Body Scrollable Content */}
          <div className="p-6 space-y-6 flex-grow overflow-y-auto">
            
            {/* Top Sponsored Ad Unit (Matching Screenshot 2 Top Card) */}
            <div className="bg-gray-900 text-white rounded-2xl p-5 space-y-3 shadow-lg border border-gray-800 relative">
              <div className="flex items-center justify-between text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                <span>Anuncio Patrocinado &bull; MetroOpinion</span>
                <span className="text-gray-500">AdSense</span>
              </div>
              <h4 className="text-xl font-black leading-tight text-white">
                Gane $5 por respuesta
              </h4>
              <p className="text-xs text-gray-300 leading-relaxed">
                Gana dinero respondiendo preguntas simples. Te pagamos en efectivo. Sencillo y divertido.
              </p>
              <a
                href="#"
                onClick={(e) => e.preventDefault()}
                className="inline-flex items-center justify-between w-full px-4 py-2.5 bg-pink-600 hover:bg-pink-700 text-white font-bold text-xs rounded-xl transition shadow"
              >
                <span>Responder Encuestas</span>
                <ChevronRight className="w-4 h-4" />
              </a>
            </div>

            {/* Gemini AI Generated Content Section */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2 text-sm font-bold text-gray-900 dark:text-white">
                  <Sparkles className="w-4 h-4 text-blue-600" />
                  <span>Explicación sobre &quot;{topic}&quot;</span>
                </div>
                <span className="text-[10px] font-medium text-gray-500 bg-gray-100 dark:bg-gray-800 px-2 py-0.5 rounded">
                  Modelo Gemini 1.5
                </span>
              </div>

              {/* Chat / Messages Box */}
              <div className="space-y-3">
                {messages.map((msg, idx) => (
                  <div
                    key={idx}
                    className={`p-4 rounded-2xl text-xs leading-relaxed ${
                      msg.sender === "gemini"
                        ? "bg-blue-50/80 dark:bg-gray-800/80 text-gray-800 dark:text-gray-200 border border-blue-100 dark:border-gray-700 shadow-xs"
                        : "bg-brand-500 text-white ml-6 font-semibold"
                    }`}
                  >
                    {msg.sender === "gemini" && (
                      <div className="flex items-center space-x-1.5 text-[11px] font-bold text-blue-600 dark:text-blue-400 mb-1.5">
                        <Bot className="w-3.5 h-3.5" />
                        <span>Resumen Asistido</span>
                      </div>
                    )}
                    <p>{msg.text}</p>
                  </div>
                ))}

                {isGenerating && (
                  <div className="p-3 bg-blue-50 dark:bg-gray-800 rounded-xl text-xs text-blue-600 flex items-center space-x-2">
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    <span>Gemini está procesando la respuesta...</span>
                  </div>
                )}
              </div>
            </div>

            {/* Related Topics Accordion inside Side Panel */}
            <div className="space-y-3 pt-2 border-t border-gray-200 dark:border-gray-800">
              <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider">Más temas de interés</h4>
              <div className="divide-y divide-gray-100 dark:divide-gray-800 bg-gray-50 dark:bg-gray-800/40 rounded-xl border border-gray-200 dark:border-gray-800">
                {["Educación y formación musical", "Historias", "Psicología"].map((item, idx) => (
                  <a
                    key={idx}
                    href="#"
                    onClick={(e) => e.preventDefault()}
                    className="p-3 flex items-center justify-between text-xs font-semibold text-gray-800 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400 transition"
                  >
                    <span>{item}</span>
                    <ChevronRight className="w-4 h-4 text-gray-400" />
                  </a>
                ))}
              </div>
            </div>
          </div>

          {/* Interactive Input Form at bottom of Drawer */}
          <div className="p-4 bg-gray-50 dark:bg-gray-800/80 border-t border-gray-200 dark:border-gray-800">
            <form onSubmit={handleSendPrompt} className="flex items-center space-x-2">
              <input
                type="text"
                value={inputQuery}
                onChange={(e) => setInputQuery(e.target.value)}
                placeholder="Pregúntale a Gemini sobre este tema..."
                className="flex-grow text-xs px-4 py-2.5 bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <button
                type="submit"
                disabled={!inputQuery.trim() || isGenerating}
                className="p-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white rounded-xl disabled:opacity-50 transition shadow-sm"
                title="Enviar consulta a Gemini"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>

        </div>
      </div>
    </div>
  );
}
